/// Contiene el segmento cliente
table VDIM_SEGMENTO_CTE
	lineageTag: ef97ebc4-ef48-4f63-85a1-f65ed823f165

	/// Llave para conexion a bandera segmento cliente
	column LLAVE_SEGMENTO_CLIENTE
		dataType: int64
		formatString: 0
		lineageTag: ff1c50f9-33de-456f-bc49-077ae714fe4f
		summarizeBy: sum
		sourceColumn: LLAVE_SEGMENTO_CLIENTE

		annotation SummarizationSetBy = Automatic

	/// Bandera de segmento cliente
	column SEGMENTO_CLIENTE
		dataType: string
		lineageTag: 77556672-d546-4f26-adf3-36f511df7dc4
		summarizeBy: none
		sourceColumn: SEGMENTO_CLIENTE

		annotation SummarizationSetBy = Automatic

	partition VDIM_SEGMENTO_CTE = m
		mode: import
		source =
				let
				    Origen = GoogleBigQuery.Database([UseStorageApi=false, BillingProject="crp-pro-cx-semantica"]),
				    #"crp-pro-cx-semantica" = Origen{[Name="crp-pro-cx-semantica"]}[Data],
				    mus_pro_negfin_shared_views_Schema = #"crp-pro-cx-semantica"{[Name="mus_pro_negfin_shared_views",Kind="Schema"]}[Data],
				    VDIM_SEGMENTO_CTE_Table = mus_pro_negfin_shared_views_Schema{[Name="VDIM_SEGMENTO_CTE",Kind="Table"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(VDIM_SEGMENTO_CTE_Table, each ([SEGMENTO_CLIENTE] <> null) and ([LLAVE_SEGMENTO_CLIENTE] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

