/// Contiene catalogo de segmento RFM
/// 
table VDIM_SEGMENTO_RFM
	lineageTag: 29db0a54-44cb-44a1-9b9c-870f9a31c302

	/// Llave para conexccion a la bandera segmento RFM
	column LLAVE_SEGMENTO_RFM
		dataType: int64
		formatString: 0
		lineageTag: 8647b28d-4d86-4fc2-a344-a8b7c4e07b45
		summarizeBy: sum
		sourceColumn: LLAVE_SEGMENTO_RFM

		annotation SummarizationSetBy = Automatic

	/// Bandera de segmento RFM
	column SEGMENTO_RFM
		dataType: string
		lineageTag: b7438d48-710d-452c-8c97-7343a7fe5535
		summarizeBy: none
		sourceColumn: SEGMENTO_RFM

		annotation SummarizationSetBy = Automatic

	partition VDIM_SEGMENTO_RFM = m
		mode: import
		source =
				let
				    Origen = GoogleBigQuery.Database([UseStorageApi=false, BillingProject="crp-pro-cx-semantica"]),
				    #"crp-pro-cx-semantica" = Origen{[Name="crp-pro-cx-semantica"]}[Data],
				    mus_pro_negfin_shared_views_Schema = #"crp-pro-cx-semantica"{[Name="mus_pro_negfin_shared_views",Kind="Schema"]}[Data],
				    VDIM_SEGMENTO_RFM_Table = mus_pro_negfin_shared_views_Schema{[Name="VDIM_SEGMENTO_RFM",Kind="Table"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(VDIM_SEGMENTO_RFM_Table, each ([SEGMENTO_RFM] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

