/// Presupuestos
table PPTO
	lineageTag: abf08190-0449-4bb2-a13c-cdb74fe14092

	/// Diferencia de Presupuesto Actual vs (REV, ME)
	measure 'DIFERENCIA PPTO' = COALESCE(PPTO[IMP_REAL],0)-COALESCE(PPTO[IMP_PLAN],0)
		lineageTag: 738a171f-eada-46c0-9ddc-873700b483db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Semaforeo  de presupuestos
	measure SEMAFORO =
			
			SWITCH(
			    TRUE(),
			    [DIFERENCIA PPTO] > 0, "POSITIVO",
			    [DIFERENCIA PPTO] < 0, "NEGATIVO"
			)
		lineageTag: a02439d1-57c7-4106-9e97-5ff779082fd7

	measure IMP_TOTAL =
			CALCULATE(
			    SUM(PPTO[IMP]),
			    FILTER(
			        PPTO,
			        PPTO[TIP_IND] >= 0 && PPTO[TIP_IND] <= 8
			    )
			)
		lineageTag: 55286628-0948-4e63-bd15-29c80174f93d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IMP_PLAN = CALCULATE([IMP_TOTAL]*1000,FILTER(PPTO,PPTO[TIP_PPTO] IN {"PPTO ME","PPTO REV"}))
		lineageTag: 97148c98-83d0-4df5-a00c-6bb0f6d29a4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IMP_REAL = CALCULATE([IMP_TOTAL],PPTO[TIP_PPTO]="REAL")
		lineageTag: e4ee0c01-95b2-4701-84c9-be15c7ff60d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IMP_TOTAL_% =
			
			CALCULATE(
			    AVERAGE(PPTO[IMP]),
			    FILTER(
			        ALL(PPTO),
			        PPTO[TIP_IND] >= 21 && PPTO[TIP_IND] <= 28
			    )
			)
		lineageTag: bb6c2be7-a020-4e8d-830b-623511be5258

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IMP_PLAN_% = CALCULATE([IMP_TOTAL_%],FILTER(PPTO,PPTO[TIP_PPTO] IN {"PPTO ME","PPTO REV"}))
		lineageTag: 9dd248c9-38a4-4808-a88a-279634440730

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Suma_Porcentajes_Seleccionados =
			
			SUMX(
			    FILTER('PPTO', 'PPTO'[TIP_IND] >= 21 && 'PPTO'[TIP_IND] <= 28),
			    'PPTO'[IMP]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 39719f7e-5ba5-430a-a6fe-b3f47ee0c516

	measure ROLADO_SDO_TOTAL_REAL =
			
			CALCULATE(
			    AVERAGE(ppto[ROLADO_SDO]),
			    ALL(ppto[TIP_PPTO])
			)
		lineageTag: 3e701188-fda0-4549-a748-9c00f19891dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIFERENCIA PPTO %' = COALESCE(PPTO[IM_REAL%],0)-COALESCE(PPTO[Suma_Porcentajes_Seleccionados],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ca40cf50-e4cd-422a-8b48-1feaef8b9e3d

	measure SEMAFORO_PPTO_% =
			
			SWITCH(
			    TRUE(),
			    [DIFERENCIA PPTO %] > 0, "POSITIVO",
			    [DIFERENCIA PPTO %] < 0, "NEGATIVO",
			    "NEUTRAL"
			)
		lineageTag: 7a471fb9-cf15-4f28-b6b4-14a83d8c3ff3

	measure Aggregate_150_210_ppto =
			
			VAR _filtro_seleccionado = SELECTEDVALUE('PPTO'[IND_DES_REAL])
			
			VAR Suma_26 = CALCULATE(SUM(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 26)
			VAR Suma_27 = CALCULATE(SUM(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 27)
			VAR Suma_28 = CALCULATE(SUM(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 28)
			
			RETURN
			    IF(
			        NOT ISBLANK(_filtro_seleccionado),
			        Suma_26 * Suma_27 * Suma_28
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e7383524-a20d-4e89-83ae-acfbf304d0a1

	measure AGGREGATE_X_120_ppto =
			
			VAR _filtro_seleccionado = SELECTEDVALUE('PPTO'[IND_DES_REAL])
			
			VAR Suma_21 = CALCULATE(AVERAGE(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 21)
			VAR Suma_22 = CALCULATE(AVERAGE(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 22)
			VAR Suma_23 = CALCULATE(AVERAGE(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 23)
			VAR Suma_24 = CALCULATE(AVERAGE(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 24)
			VAR Suma_25 = CALCULATE(AVERAGE(ppto[IMP]), REMOVEFILTERS('PPTO'[IND_DES_REAL]), ppto[TIP_IND] = 25)
			
			RETURN
			    IF(
			        NOT ISBLANK(_filtro_seleccionado),
			        Suma_21 * Suma_22 * Suma_23 * Suma_24 * Suma_25,
			        BLANK()
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b4b2fc8c-eb54-4bbb-8d8e-e1be62a59248

	measure IND_DES_REAL_SELECCIONADO = ```
			
			                            SELECTEDVALUE('PPTO'[IND_DES_REAL],"All")
			```
		lineageTag: 1feade24-0fe3-4728-b846-13705521e6ec

	measure AGGREGATE_REAL_X_120 =
			
			VAR Rolado2 = CALCULATE('PPTO'[IM_REAL%], PPTO[IND_DES_REAL] = "2.-1-29")
			VAR Rolado3 = CALCULATE('PPTO'[IM_REAL%], PPTO[IND_DES_REAL] = "3.-30")
			VAR Rolado4 = CALCULATE('PPTO'[IM_REAL%], PPTO[IND_DES_REAL] = "4.-60")
			VAR Rolado5 = CALCULATE('PPTO'[IM_REAL%], PPTO[IND_DES_REAL] = "5.-90")
			VAR Rolado6 = CALCULATE('PPTO'[IM_REAL%], PPTO[IND_DES_REAL] = "6.-120")
			
			RETURN
			    COALESCE(Rolado2, 0) *
			    COALESCE(Rolado3, 0) *
			    COALESCE(Rolado4, 0) *
			    COALESCE(Rolado5, 0) *
			    COALESCE(Rolado6, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f4163c11-042b-4a08-ad58-ecfb9aa22728

	measure Agregate_150_210_REAL_Final =
			
			VAR Rolado6 = CALCULATE(
			    'PPTO'[IM_REAL%],
			    'PPTO'[IND_DES_REAL] = "7.-150"
			)
			VAR Rolado7 = CALCULATE(
			    'PPTO'[IM_REAL%],
			    'PPTO'[IND_DES_REAL] = "8.-180"
			)
			VAR Rolado8 = CALCULATE(
			    'PPTO'[IM_REAL%],
			    'PPTO'[IND_DES_REAL] = "9.-210"
			)
			RETURN
			    Rolado6 * Rolado7 * Rolado8
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 614c3e4d-3e0e-4522-bc72-57c16210e884

	measure IM_REAL% =
			
			CALCULATE(
			    DIVIDE(SUM(PPTO[IMP]), SUM(PPTO[IMP_ANT])),
			    PPTO[tip_ppto] = "real"
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: abf77e0b-13a5-44de-ab1e-86328db564bb

	/// Organización
	column TIP_INF
		dataType: double
		formatString: 0
		lineageTag: fd20ce2f-025d-4a1b-9fd1-7a5c52d52117
		summarizeBy: none
		sourceColumn: TIP_INF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Tipo de presupuesto
	column TIP_PPTO
		dataType: string
		lineageTag: 635fd98b-1b4b-4f2c-b809-2f95079fc2a5
		summarizeBy: none
		sourceColumn: TIP_PPTO

		annotation SummarizationSetBy = Automatic

	/// Importe
	column IMP
		dataType: double
		lineageTag: 653026a8-7841-4026-8693-79924821ee1c
		summarizeBy: sum
		sourceColumn: IMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Agrupación Año - Mes
	column ANIOMES
		dataType: double
		lineageTag: d2789b1e-0624-49d6-8176-79c4962db92b
		summarizeBy: none
		sourceColumn: ANIOMES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Descripción de organización 
	column PRODUCTO = ```
			IF(PPTO[TIP_INF] = 100 ,"LPC", 
			         IF(PPTO[TIP_INF] = 110 ,"DILISA", 
			        IF(PPTO[TIP_INF] = 200 ,"SUBURBIA VISA",
			        IF(PPTO[TIP_INF] = 210 ,"SUBURBIA DEPARTAMENTAL",
			         IF(PPTO[TIP_INF] IN {220,230},"MINI PAGOS (CC)","")))))
			```
		lineageTag: 3323fecf-4bf7-4ff7-8ab2-060c6b6c625e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TIP_IND
		dataType: double
		formatString: #,0
		lineageTag: 46b9162f-8ca7-4601-9b77-11139dcfcd98
		summarizeBy: sum
		sourceColumn: TIP_IND

		annotation SummarizationSetBy = Automatic

	column IND_DES
		dataType: string
		lineageTag: b29178ec-e2ff-46e2-b5bb-8067f08d9fde
		summarizeBy: none
		sourceColumn: IND_DES

		annotation SummarizationSetBy = Automatic

	column CTAS
		dataType: double
		lineageTag: 3ce85f09-382e-41ed-a865-91632e7ce9d3
		summarizeBy: sum
		sourceColumn: CTAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANIO
		dataType: double
		lineageTag: 590f7d24-a96c-4340-a941-7d2472585809
		summarizeBy: sum
		sourceColumn: ANIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MES
		dataType: int64
		lineageTag: 30f258ff-8ef6-4f88-bc2b-74795738ec97
		summarizeBy: sum
		sourceColumn: MES

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IND_DES_REAL
		dataType: string
		lineageTag: 9fd78b56-ff5a-4723-ae3f-a5ec0293b11c
		summarizeBy: none
		sourceColumn: IND_DES_REAL

		annotation SummarizationSetBy = Automatic

	column ROLADO_SDO
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7a1e1031-af1f-49f3-b430-6149e24d3ecd
		summarizeBy: sum
		sourceColumn: ROLADO_SDO

		annotation SummarizationSetBy = Automatic

	column ROLADO_CTA
		dataType: double
		lineageTag: 4020ddd7-ce86-495d-b443-dd3a1551f58b
		summarizeBy: sum
		sourceColumn: ROLADO_CTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IMP_ANT
		dataType: double
		lineageTag: 946db959-8fb7-4a0d-83ce-dac2226524b4
		summarizeBy: sum
		sourceColumn: IMP_ANT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition PPTO = m
		mode: import
		source =
				let
				    Origen = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="crp-pro-cx-analitica"]){[Name="crp-pro-cx-analitica"]}[Data], "SELECT ANIO,MES,#(lf)       TIP_INF,#(lf)       TIP_PPTO,#(lf)       IND_DES,#(lf)       TIP_IND,#(lf)       IMP,#(lf)       NULL AS IMP_ANT,#(lf)       CTAS,#(lf)      (ANIO*100+MES) as ANIOMES,#(lf)      CASE WHEN IND_DES = '1.-1-29 DIAS($%)' OR IND_DES = '1.-1-29 DIAS' THEN '2.-1-29'#(lf)           WHEN IND_DES = '2.-30_DIAS($%)' OR IND_DES = '2.-30_DIAS' THEN '3.-30' #(lf)           WHEN IND_DES = '3.-60_DIAS($%)' OR IND_DES = '3.-60_DIAS' THEN '4.-60'#(lf)           WHEN IND_DES = '4.-90_DIAS($%)' OR IND_DES = '4.-90_DIAS' THEN '5.-90'#(lf)           WHEN IND_DES = '5.-120_DIAS($%)' OR IND_DES = '5.-120_DIAS'THEN '6.-120'#(lf)           WHEN IND_DES = '6.-150_DIAS($%)' OR IND_DES = '6.-150_DIAS'THEN '7.-150'#(lf)           WHEN IND_DES = '7.-180_DIAS($%)' OR IND_DES = '7.-180_DIAS' THEN '8.-180'#(lf)           WHEN IND_DES = '8.-210_DIAS($%)' OR IND_DES = '8.-210_DIAS' THEN '9.-210'#(lf)           ELSE  'OTRO' END AS IND_DES_REAL,#(lf)      NULL AS ROLADO_SDO,#(lf)      NULL AS ROLADO_CTA#(lf)FROM crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_CAT_PRESUPUESTO#(lf)WHERE ANIO >=2023#(lf)AND TIP_PPTO IN ('PPTO REV','PPTO ME')#(lf)AND TIP_IND IN (0,1,2,3,4,5,6,7,8,9,10,11,21,22,23,24,25,26,27,28)#(lf)UNION ALL#(lf)SELECT ANIO,MES,TIP_INF,'REAL' AS TIP_PPTO,NIV_MOR AS IND_DES,#(lf)       CASE WHEN NIV_MOR = '0.-CTAS_VIG' THEN 0#(lf)            WHEN NIV_MOR = '1.-1-29 DIAS' THEN 1#(lf)            WHEN NIV_MOR = '2.-30_DIAS' THEN 2#(lf)            WHEN NIV_MOR = '3.-60_DIAS' THEN 3#(lf)            WHEN NIV_MOR = '4.-90_DIAS' THEN 4#(lf)            WHEN NIV_MOR = '5.-120_DIAS' THEN 5#(lf)            WHEN NIV_MOR = '6.-150_DIAS' THEN 6#(lf)            WHEN NIV_MOR = '7.-180_DIAS' THEN 7#(lf)            ELSE 8 END AS TIP_IND,#(lf)        SUM_SDO_ACT AS IMP,#(lf)        SDO_ANT AS IMP_ANT,#(lf)        CTAS,#(lf)        ANIOMES,#(lf)        CASE WHEN NIV_MOR = '0.-CTAS_VIG' THEN '1.-CTAS_VIG'#(lf)             WHEN NIV_MOR = '1.-1-29 DIAS' THEN '2.-1-29'#(lf)             WHEN NIV_MOR = '2.-30_DIAS' THEN '3.-30' #(lf)             WHEN NIV_MOR = '3.-60_DIAS' THEN '4.-60'#(lf)             WHEN NIV_MOR = '4.-90_DIAS' THEN '5.-90'#(lf)             WHEN NIV_MOR = '5.-120_DIAS'THEN '6.-120'#(lf)             WHEN NIV_MOR = '6.-150_DIAS'THEN '7.-150'#(lf)             WHEN NIV_MOR = '7.-180_DIAS' THEN '8.-180'#(lf)             WHEN NIV_MOR= '8.-210_DIAS' THEN '9.-210'#(lf)           ELSE  'OTRO' END AS IND_DES_REAL,#(lf)        ROLADO_SDO,#(lf)        ROLADO_CTAS #(lf)FROM `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.FAC_NEGFIN_ROLADO_TOT`#(lf)WHERE ANIO >= 2023", null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Origen, each true)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

